version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    links:
    - db
    volumes:
    - .:/usr/src/app
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      PORT: ${DB_PORT}

 
      

volumes: 
 data: {}